<?php
/**
 * @var \Amasty\UserName\Block\Index $block
 */
?>

<form class="<?= $this->getCssClasses() ?>" method="post">
    <div>
        <label for="sku">sku:</label>
        <input type="text" name="sku" />
    </div>
    <div>
        <label for="qty">qty:</label>
        <input type="number" name="qty" />
    </div>
    <?= $block->getChildHtml('Amasty_USERNAME.timer') ?>
    <div>
        <button type="button">button</button>
    </div>
</form>