<?php
/**
 * @var \Amasty\UserName\Block\Form $block
 */
?>

<form class="<?= $block->getCssClasses() ?>" action="username/index/addtocart" method="post">
    <div>
        <label for="sku">sku:</label>
        <input type="text" name="sku" />
    </div>
    <?php if (!$block->isQtyHidden()): ?>
        <div>
            <label for="qty">qty:</label>
            <input type="number" name="qty" value="<?= $block->getDefaultQtyValue() ?>" />
        </div>
    <?php endif; ?>
    <?= $block->getChildHtml('Amasty_USERNAME.timer') ?>
    <div>
        <button type="submit">button</button>
    </div>
</form>